export const SET_PLACES = "SET_PLACES";
export const REMOVE_USER = "REMOVE_USER";
export const TRY_AUTH = 'TRY_AUTH';

export const UI_START_LOADING = "UI_START_LOADING";

export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";

export const AUTH_SET_USERID = "AUTH_SET_USERID";

export const AUTH_LOGIN_USER = "AUTH_LOGIN_USER";

export const ADD_USER_INFO = "ADD_USER_INFO";

export const SET_USER_INFO = "SET_USER_INFO";

export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const SET_USER_INTREST = "SET_USER_INTREST";

export const REMOVE_INTREST_REQUEST = "REMOVE_INTREST_REQUEST";

export const SET_USER_RECEIVED_INTREST = "SET_USER_RECEIVED_INTREST";

export const REMOVE_USER_RECEIVED_INTREST = "REMOVE_USER_RECEIVED_INTREST";
 
export const SET_USER_MATCH = "SET_USER_MATCH";